// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package client

import (
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type RevCatGraphQLClient interface {
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli *http.Client, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) RevCatGraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Query struct {
	Search           SearchResult      "json:\"search\" graphql:\"search\""
	MediathekEntries []*MediathekEntry "json:\"mediathekEntries,omitempty\" graphql:\"mediathekEntries\""
}

var DocumentOperationNames = map[string]string{}
