# This file is a template, and might need editing before it works on your project.
image: golang:latest

default:
  tags:
    - docker

variables:
  REPO_NAME: git.punkt.de/$CI_PROJECT_PATH_SLUG

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - go mod tidy
    - go mod download
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/revcat ./cmd/revcat 
  artifacts:
    paths:
      - revcat

dockerdeploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - ls -la
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
