# Build, publish and deploy only for v* tags.
workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
    - when: never

include:
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/build@main
    inputs:
      name: revcat
      cmd_path: ./cmd/revcat
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/publish@main
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/deploy@main
    inputs:
      service_name: revcat
      deployment_host: v001340.fhnw.ch

stages:
  - build
  - publish
  - deploy
