include:
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/build@main
    inputs:
      name: revcat
      cmd_path: ./cmd/revcat
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/publish@main
  - component: $CI_SERVER_FQDN/fhnw/fhnw-ink-app/fhnw-go-docker-deploy/deploy@main
    inputs:
      service_name: revcat
      deployment_host: v001340.fhnw.ch

stages:
  - build
  - publish
  - deploy
