// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Facet struct {
	Key    string        `json:"key"`
	Values []*FacetValue `json:"values"`
}

type FacetInput struct {
	Key          string   `json:"key"`
	ValuesString []string `json:"valuesString,omitempty"`
	ValuesInt    []int    `json:"ValuesInt,omitempty"`
}

type FacetValue struct {
	ValStr *string `json:"valStr,omitempty"`
	ValInt *int    `json:"valInt,omitempty"`
	Count  int     `json:"count"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Media struct {
	Name        string  `json:"name"`
	Mimetype    string  `json:"mimetype"`
	Pronom      *string `json:"pronom,omitempty"`
	Type        string  `json:"type"`
	URI         string  `json:"uri"`
	Orientation *int    `json:"orientation,omitempty"`
	Fulltext    *string `json:"fulltext,omitempty"`
	Width       *int    `json:"width,omitempty"`
	Height      *int    `json:"height,omitempty"`
	Length      *int    `json:"length,omitempty"`
}

type MediaList struct {
	Name  string   `json:"name"`
	Items []*Media `json:"items"`
}

type MediathekEntry struct {
	ID                string            `json:"id"`
	Signature         string            `json:"signature"`
	SignatureOriginal string            `json:"signatureOriginal"`
	Source            string            `json:"source"`
	Title             string            `json:"title"`
	Series            *string           `json:"series,omitempty"`
	Place             *string           `json:"place,omitempty"`
	Date              *string           `json:"date,omitempty"`
	Category          []string          `json:"category,omitempty"`
	Tags              []string          `json:"tags,omitempty"`
	Notes             []string          `json:"notes,omitempty"`
	URL               *string           `json:"url,omitempty"`
	Abstract          *string           `json:"abstract,omitempty"`
	References        []*MediathekEntry `json:"references,omitempty"`
	Publisher         *string           `json:"publisher,omitempty"`
	Rights            *string           `json:"rights,omitempty"`
	License           *string           `json:"license,omitempty"`
	Type              *string           `json:"type,omitempty"`
	Extra             []*KeyValue       `json:"extra,omitempty"`
	Media             []*MediaList      `json:"media,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool   `json:"hasNextPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type SearchResult struct {
	TotalCount int               `json:"totalCount"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	Edges      []*MediathekEntry `json:"edges"`
	Facets     []*Facet          `json:"facets"`
}
